spring:
  application:
    name: order-service
  cloud:
    kubernetes:
      enabled: false
server:
  port: 8082
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}